services:
  one-fit-postgres:
    image: postgres:16
    container_name: restaurants
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: restaurants
  one-fit-redis:
    container_name: restaurants-redis
    image: redis:7.2.4
    ports:
      - "6378:6379"
