spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5431/postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update